services:
  postgres:
    container_name: api
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=api
      - POSTGRES_MAX_CONNECTIONS=100
      - POSTGRES_IDLE_IN_TRANSACTION_SESSION_TIMEOUT=60000
      - POSTGRES_TCP_KEEPALIVES_IDLE=600
      - POSTGRES_TCP_KEEPALIVES_INTERVAL=60
      - POSTGRES_TCP_KEEPALIVES_COUNT=10
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
volumes:
  data:
